resume: 
pretrain: /home/mtech/project_env/BIKE/output/k400/ViT-B/16/k400-vit-b-16-f8.pt #/home/mtech/project_env/BIKE/output/k400/ViT-B/32/20230611_204803/model_best.pt #/ #/home/mtech/project_env/BIKE/output/k400/ViT-L/14/20230622_214758/model_best.pt
seed: 1024
data:
    dataset: ucf101
    modality: RGB
    num_segments: 8
    seg_length: 1
    batch_size: 4
    workers: 4
    num_classes: 101
    image_tmpl: 'image_{:04d}.jpg'
    # train_root: '/bpfs/v2_mnt/VIS/test/k400/train_320_frames'
    train_root: '/home/mtech/project_env/mmaction2/tools/data/ucf101/UCF101_frames'
    # train_list: 'lists/k400/kinetics_rgb_train_se320.txt'
    train_list: '/home/mtech/project_env/mmaction2/tools/data/ucf101/UCF101_frames.txt' 
    # val_root: /bpfs/v2_mnt/VIS/test/k400/kinetics_400_val_320_opencv
    # val_list: lists/k400/kinetics_rgb_val_se320.txt
    # label_list: 'lists/k400/kinetics_400_labels.csv'
    val_root: /home/mtech/project_env/mmaction2/tools/data/ucf101/UCF101_val_frames
    val_list: /home/mtech/project_env/mmaction2/tools/data/ucf101/UCF101_val_frames.txt
    label_list: '/home/mtech/project_env/mmaction2/tools/data/ucf101/ucf_labels.csv'
    pose_root: '/home/mtech/project_env/mmaction2/tools/data/ucf101/UCF101_frames_pose'
    pose_list: '/home/mtech/project_env/mmaction2/tools/data/ucf101/UCF101_frames.txt' 
    pose_val_root: '/home/mtech/project_env/mmaction2/tools/data/ucf101/UCF101_frames_pose_val'
    pose_val_list: '/home/mtech/project_env/mmaction2/tools/data/ucf101/UCF101_val_frames.txt' 
    input_size: 224
    random_shift: True
    output_path: output
network:
    arch:  ViT-B/16 #ViT-B/16 ##ViT-L/14  
    init: True
    tm: False
    drop_out: 0.0 
    emb_dropout: 0.0
    sim_header: Transf  # Transf   None  
    interaction: VCS  # DP VCS
    joint_st: False
    drop: 0      
    fix_text: True  
    fix_video: False        
solver:
    type: cosine
    epochs: 30
    start_epoch: 0
    epoch_offset: 0
    optim: adamw
    lr: 5.e-5
    lr_warmup_step: 5
    weight_decay: 0.2
    loss_type: NCE
    evaluate: False
    clip_ratio: 0.1
    grad_accumulation_steps: 8
logging:
    print_freq: 10
    eval_freq: 2